### ISSUE TITLE
`xwidget-webkit-browse-url` not working on debian testing with emacs 27.1 beta snap

### ISSUE THREAD

**Issue by egh** [alexmurray/emacs-snap#21]
On a debian testing machine, with snap emacs beta, `(xwidget-webkit-browse-url "http://example.org/")` does not display anything for me.
![image](https://user-images.githubusercontent.com/22718/93004789-3f0ee500-f4ff-11ea-985f-c56bd48a51cc.png)

```
emacs              27.1                        857   latest/beta    alexmurray    classic
```

```
  Operating System: Debian GNU/Linux bullseye/sid
            Kernel: Linux 5.7.0-3-amd64
      Architecture: x86-64
```

On my ubuntu 20.04 machine, running the snap emacs beta, I can run `(xwidget-webkit-browse-url "http://example.org/")` (starting emacs with `emacs -Q`) and it works fine.

![image](https://user-images.githubusercontent.com/22718/93004802-6f568380-f4ff-11ea-921e-9867acc84b59.png)

```
emacs              27.1                        857   latest/beta      alexmurray         classic
```

```
  Operating System: Ubuntu 20.04.1 LTS
            Kernel: Linux 5.4.0-45-generic
      Architecture: x86-64
```

**Comment by alexmurray** [comment]
Thanks for reporting this issue - it seems that even though we bundle the various webkit2gtk libraries within the snap, it still tries and uses the ones from the host - on Ubuntu 20.04 these basically match what is in Ubuntu 18.04  and so there is no incompatibility but I am guessing that the ones shipped in Debian testing perhaps differ by a bit and so causes this issue. To fix this we need to find a way to ensure the emacs snap uses these libraries that it ships itself rather than the ones from the host. I will keep investigating and keep you posted if I find anything (I am able to reproduce it so hopefully I can devise some fix...).

**Comment by rassie** [comment]
If I understand correctly, `xwidgets` support has been disabled soon after this issue was opened (in https://github.com/alexmurray/emacs-snap/commit/733f3238670ff5987c886ba8d0758a9169ff77e6), which is a shame, but perfectly understandable given the problems. In the meantime, two years have passed -- are you aware of any movement on the `snap` front to fix this problem? Is there a relevant issue we could try to hype up a bit?

**Comment by alexmurray** [comment]
The issue is webkitgtk itself hard-codes the path to libwebkit - so for the snap we would have to build webkitgtk from source and patch it I suspect (rather than just using the deb from Ubuntu) - so this is an upfront burden to implement plus would be an ongoing maintenance burden to handle each time webkitgtk has a new security update. At this time I do not have the resources to look into this more so I do not have any plans to try and resolve this any time soon unfortunately.

**Comment by alexmurray** [comment]
There are no plans to support webkit in the emacs-snap.
