### ISSUE TITLE
Any plans to add `pgtk` branch to the mix?

### ISSUE THREAD

**Issue by rassie** [alexmurray/emacs-snap#23]
Apparently, there are two hot 28.x branches right now: `gccemacs` and [`pgtk`](https://github.com/masm11/emacs/tree/pgtk). Both seem to be game-changers in their own domain, to the point that both are included in many emacs 28.x binary compilation.

Since `gccemacs` is already included in the `edge` branch of this snap and it is expected that both on these branches will get merged in the 28.x release cycle, are there any plans to include the `pgtk` branch in the snap?

**Comment by rassie** [comment]
Maybe you could just make use of https://github.com/flatwhatson/emacs, which is used to make regular builds already.

**Comment by alexmurray** [comment]
Thanks for raising this issue - pgtk is something I have been meaning to check out for a while. I am a bit concerned however about rolling this into the edge channel as well as nativecomp since I am a bit worried about conflicts between the two branches. Currently they don't merge without conflict and I would prefer to have a solution I can automate via the snapcraft.yaml to build from the official upstream mirror rather than someone else's fork. So until they can be merged without conflict this will have to remain a wishlist item.

**Comment by rassie** [comment]
`native-comp` has been merged to `master`, but the `pgtk` branch sadly looks somewhat stale :( Would you pick it if it got rebased on `master`?

**Comment by alexmurray** [comment]
I'd be happy to take a look and see if we can include it if it merges cleanly.

**Comment by rassie** [comment]
I think this is largely obsolete now. It seems the `pgtk` branch is due to be merged into `master` soon-ish, so it will should be available from the `edge` channel in the future. Good enough to close?

**Comment by alexmurray** [comment]
Fine by me - thanks @rassie
