### ISSUE TITLE
xwidgets support

### ISSUE THREAD

**Issue by MrMic** [alexmurray/emacs-snap#33]
Hi,

- Thanks for your work, but with emacs 28 xwidgets support is not part of the compilation.
- Can you release one with that included?
- I need it with mu4e-views for reading HTML email correctly in mu4e.
Rgds,
Michaël C.

**Comment by alexmurray** [comment]
Apologies for the delay in responding to this issue - the problem with webkit is that it doesn't support the different `/snap/` prefix which the emacs snap uses - as such, if we build with webkit/xwidgets support then emacs tries to use the webkit library from the host filesystem which will likely be a different version and then emacs crashes due to the different ABI. Please see the existing issue https://github.com/alexmurray/emacs-snap/issues/21 which captures this.
