### ISSUE TITLE
tree-sitter support

### ISSUE THREAD

**Issue by sonofjon** [alexmurray/emacs-snap#51]
Emacs 30 (and 29) needs to be built with --with-tree-sitter flag to enable tree-sitter support.

**Comment by alexmurray** [comment]
Turns out the aforementioned fixes were not correct (tree-sitter is not packaged for Ubuntu 20.04 LTS which is what the emacs snap is based off). So instead have added support to compile tree-sitter manually in https://github.com/alexmurray/emacs-snap/commit/8ff35dbc86f9bbd53c3005fce8d376973c8c330b - this is now available on the edge channel.
