### ISSUE TITLE
Tried the snap install emacs, but how to run etags?

### ISSUE THREAD

**Issue by mattiasw2** [alexmurray/emacs-snap#7]
Do I need to add anything to the path?

**Comment by alexmurray** [comment]
Snap package commands are exposed in the form of `packagename.command` - so the emacs snap provides the `emacs`, `emacsclient`, `etags` etc commands but these are namespaced to `emacs.etags`, `emacs.emacsclient` etc. So you can run `emacs.etags` to run `etags`.

However, snap commands can then have aliases - so you could set up an `etags` alias as:

```sudo snap alias emacs.etags etags```

So then you can run `etags` without the `emacs.` prefix.

The snap store provides a default alias for `emacs` itself since it is the name of the package - so that is why there is no `emacs.emacs` command and so no specific alias is needed for `emacs`.
